# Generated by Django 3.1.4 on 2020-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201203_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
