# Generated by Django 3.1.4 on 2020-12-03 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stream_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
