# Generated by Django 3.1.4 on 2020-12-03 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201203_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerrecord',
            name='viewing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewing_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
