# Generated by Django 3.1.4 on 2020-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201205_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_color',
            field=models.CharField(default='#121212', max_length=7),
        ),
    ]
